import { EmailAccount, EmailBlacklistEntry, EmailLog } from './email-admin.models';

export const EMAIL_ACCOUNTS_MOCK: EmailAccount[] = [
  {
    id: 1,
    code: 'MAIL_FACT_01',
    name: 'Facturacion principal',
    provider: 'Microsoft 365',
    fromAddress: 'facturacion@epmapat.gob.ec',
    fromName: 'ERP Facturacion',
    replyTo: 'soporte.facturacion@epmapat.gob.ec',
    transportType: 'SMTP',
    host: 'smtp.office365.com',
    port: 587,
    protocol: 'smtp',
    securityType: 'STARTTLS',
    authRequired: true,
    username: 'facturacion@epmapat.gob.ec',
    password: '**********',
    active: true,
    defaultAccount: true,
    defaultForType: 'FACTURACION',
    lastConnectionCheck: '2026-03-27T10:18:00',
  },
  {
    id: 2,
    code: 'MAIL_NOTI_01',
    name: 'Notificaciones institucionales',
    provider: 'HTTP API',
    fromAddress: 'notificaciones@epmapat.gob.ec',
    fromName: 'Centro de Notificaciones',
    replyTo: 'mesa.ayuda@epmapat.gob.ec',
    transportType: 'API_HTTP',
    apiUrl: 'https://api.mail.example/send',
    apiAuthHeader: 'Authorization',
    apiAuthScheme: 'Bearer',
    apiKey: '**********F0B38',
    hasApiKey: true,
    active: true,
    defaultAccount: false,
    defaultForType: 'NOTIFICACION',
    lastConnectionCheck: '2026-03-26T17:40:00',
  },
  {
    id: 3,
    code: 'MAIL_CUST_01',
    name: 'Campanas y avisos',
    provider: 'Proveedor SMTP legado',
    fromAddress: 'comunicaciones@epmapat.gob.ec',
    fromName: 'Comunicaciones ERP',
    replyTo: 'comunicaciones@epmapat.gob.ec',
    transportType: 'SMTP',
    host: 'smtp.epmapat.local',
    port: 465,
    protocol: 'smtp',
    securityType: 'SSL_TLS',
    authRequired: true,
    username: 'comunicaciones',
    password: '********',
    active: false,
    defaultAccount: false,
    defaultForType: 'CUSTOM',
    lastConnectionCheck: '2026-03-22T09:05:00',
  },
];

export const EMAIL_LOGS_MOCK: EmailLog[] = [
  {
    id: '98f78a1c-2a67-4e4c-a0d8-13fc9150d001',
    subject: 'Factura electronica FAC-2026-000184',
    type: 'DOC_ELECTRONICO',
    state: 'SENT',
    fromAddress: 'facturacion@epmapat.gob.ec',
    accountId: 1,
    accountCode: 'MAIL_FACT_01',
    accountName: 'Facturacion principal',
    to: ['cliente1@acme.com'],
    cc: ['archivo@epmapat.gob.ec'],
    bcc: [],
    attempts: 1,
    correlationId: 'FAC-2026-000184',
    lastError: '',
    createdAt: '2026-03-27T08:10:00',
    sentAt: '2026-03-27T08:11:23',
    body: '<p>Adjuntamos su factura electronica y comprobante autorizado.</p>',
    attachments: [
      { name: 'FAC-2026-000184.xml', sizeLabel: '84 KB' },
      { name: 'FAC-2026-000184.pdf', sizeLabel: '211 KB' },
    ],
  },
  {
    id: 'f92cc78d-b9fd-4761-87ab-13fc9150d002',
    subject: 'Aviso de suspension preventiva',
    type: 'NOTIFICACION',
    state: 'FAILED',
    fromAddress: 'notificaciones@epmapat.gob.ec',
    accountId: 2,
    accountCode: 'MAIL_NOTI_01',
    accountName: 'Notificaciones institucionales',
    to: ['usuario@hotmail.com'],
    cc: [],
    bcc: [],
    attempts: 3,
    correlationId: 'SUSP-2026-03-27-0007',
    lastError: '550 Recipient host policy rejection',
    createdAt: '2026-03-27T09:40:00',
    sentAt: '2026-03-27T09:42:10',
    body: '<p>Su cuenta presenta novedades pendientes de regularizacion.</p>',
    attachments: [],
  },
  {
    id: '0b3a338a-94d5-4b76-bc52-13fc9150d003',
    subject: 'Recordatorio de pago convenio 4558',
    type: 'CUSTOM',
    state: 'PENDING',
    fromAddress: 'comunicaciones@epmapat.gob.ec',
    accountId: 3,
    accountCode: 'MAIL_CUST_01',
    accountName: 'Campanas y avisos',
    to: ['cobranzas@proveedor.com', 'gerencia@proveedor.com'],
    cc: [],
    bcc: ['auditoria@epmapat.gob.ec'],
    attempts: 1,
    correlationId: 'COB-4558-20260327',
    lastError: '',
    createdAt: '2026-03-27T10:02:00',
    body: '<p>Se agenda reintento de notificacion de pago.</p>',
    attachments: [{ name: 'detalle-convenio-4558.pdf', sizeLabel: '152 KB' }],
  },
  {
    id: '8e651540-3db8-47e7-8332-13fc9150d004',
    subject: 'Comprobante de retencion listo',
    type: 'DOC_ELECTRONICO',
    state: 'CANCELLED',
    fromAddress: 'facturacion@epmapat.gob.ec',
    accountId: 1,
    accountCode: 'MAIL_FACT_01',
    accountName: 'Facturacion principal',
    to: ['contabilidad@contratista.ec'],
    cc: [],
    bcc: [],
    attempts: 0,
    correlationId: 'RET-2026-1191',
    lastError: 'Proceso cancelado por operador antes del envio',
    createdAt: '2026-03-26T16:10:00',
    body: '<p>Correo anulado por correccion del documento asociado.</p>',
    attachments: [{ name: 'retencion-1191.pdf', sizeLabel: '95 KB' }],
  },
];

export const EMAIL_BLACKLIST_MOCK: EmailBlacklistEntry[] = [
  {
    id: 1,
    type: 'DOMAIN',
    value: 'gmail.com',
    reason: 'Bloqueo temporal para pruebas internas y control de fuga de informacion.',
    active: true,
    createdAt: '2026-03-12T11:10:00',
  },
  {
    id: 2,
    type: 'HOST',
    value: 'mx.hotmail.com',
    reason: 'Host con rechazos recurrentes por politica remota.',
    active: true,
    createdAt: '2026-03-20T09:20:00',
  },
  {
    id: 3,
    type: 'EMAIL',
    value: 'usuario@dominioempresa.com',
    reason: 'Destinatario solicitado por auditoria para no recibir comunicaciones.',
    active: false,
    createdAt: '2026-02-28T15:48:00',
  },
];
