import { Asientos } from "./asientos.model";
import { Autorizaxbene } from "./autorizaxbene.model";
import { Documentos } from "../administracion/documentos.model";
import { Beneficiarios } from "./beneficiarios.model";
import { Tabla01 } from "./tabla01.model";
import { Tabla15 } from "./tabla15.model";
import { Tabla17 } from "./tabla17.model";

export class Retenciones {
	idrete: number;
	fecharegistro: Date;
	secretencion1: String;
	fechaemision: Date;
	fechaemiret1: Date;
	numdoc: String;
	porciva: number;
	swretencion: number;
	baseimponible: number;
	baseimpgrav: number;
	basenograiva: number;
	baseimpice: number;
	montoiva: number;
	porcentajeice: number;
	montoice: number;
	montoivabienes: number;
	codretbienes: String;
	porretbienes: number;
	valorretbienes: number;
	montoivaservicios: number;
	codretservicios: String;
	porretservicios: number;
	valorretservicios: number;
	montoivaserv100: number;
	codretserv100: String;
	porretserv100: number;
	valretserv100: number;
	baseimpair: number;
	codretair: String;
	porcentajeair: number;
	valretair: number;
	numautoriza: String;
	numserie: String;
	fechacaduca: Date;
	descripcion: String;
	idasiento: Asientos;
	idbene: Beneficiarios;
	intdoc: Documentos;
	idautoriza: Autorizaxbene;
	idtabla01: Tabla01;
	idtabla15: Tabla15;
	idtabla5c_100: number;
	idtabla5c_bie: number;
	idtabla5c_ser: number;
	claveacceso: String;
	numautoriza_e: String;
	fecautoriza: String;
	estado: number;
	ambiente: String;
	autorizacion: String;
	swelectro: number;
	idtabla17: Tabla17;
	inttra: number;
	usucrea: number;
	feccrea: Date;
	usumodi: number;
	fecmodi: Date;
	escoge: number;
}
